<a href="https://colab.research.google.com/github/ProcessDoctor/MIT_ClassNote/blob/main/Loading_Data_and_Initial_Data_Exploration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.float_format", lambda x: "%.3f" %x) #to restrict any float number to 3dp

In [ ]:
#accessing my file from my google drive
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
#importing the dataset to be utilized
path= "/content/drive/MyDrive/Week 1  Foundations Python and Statistics/Melbourne_Housing.csv"
data=pd.read_csv(path)

In [ ]:
#viewing the data
data.head(5)

,Suburb,Rooms,Type,SellerG,Date,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Regionname,Propertycount,Price
0,Airport West,3,t,Nelson,03-09-2016,13.500,3042.000,3.000,2.000,1.000,303.000,225,2016.000,Western Metropolitan,3464,840000
1,Albert Park,2,h,hockingstuart,03-09-2016,3.300,3206.000,2.000,1.000,0.000,120.000,82,1900.000,Southern Metropolitan,3280,1275000
2,Albert Park,2,h,Thomson,03-09-2016,3.300,3206.000,2.000,1.000,0.000,159.000,inf,NaN,Southern Metropolitan,3280,1455000
3,Alphington,4,h,Brace,03-09-2016,6.400,3078.000,3.000,2.000,4.000,853.000,263,1930.000,Northern Metropolitan,2211,2000000
4,Alphington,3,h,Jellis,03-09-2016,6.400,3078.000,3.000,2.000,2.000,208.000,inf,2013.000,Northern Metropolitan,2211,1110000

In [ ]:
data.tail(3)

,Suburb,Rooms,Type,SellerG,Date,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Regionname,Propertycount,Price
27111,Roxburgh Park,4,h,Raine,30-09-2017,20.600,3064.000,4.000,2.000,2.000,NaN,225,1995.000,Northern Metropolitan,5833,591000
27112,Springvale South,3,h,Harcourts,30-09-2017,22.200,3172.000,3.000,2.000,1.000,544.000,NaN,NaN,South-Eastern Metropolitan,4054,780500
27113,Westmeadows,4,h,Barry,30-09-2017,16.500,3049.000,4.000,2.000,6.000,813.000,140,1960.000,Northern Metropolitan,2474,791000

In [ ]:
#Shape of my dataset
data.shape
print("There are", data.shape[0], "rows and", data.shape[1], "columns.")

There are 27114 rows and 16 columns.

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27114 entries, 0 to 27113
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         27114 non-null  object
 1   Rooms          27114 non-null  int64
 2   Type           27114 non-null  object
 3   SellerG        27114 non-null  object
 4   Date           27114 non-null  object
 5   Distance       27113 non-null  float64
 6   Postcode       27113 non-null  float64
 7   Bedroom        20678 non-null  float64
 8   Bathroom       20672 non-null  float64
 9   Car            20297 non-null  float64
 10  Landsize       17873 non-null  float64
 11  BuildingArea   10543 non-null  object
 12  YearBuilt      11985 non-null  float64
 13  Regionname     27114 non-null  object
 14  Propertycount  27114 non-null  int64
 15  Price          27114 non-null  int64
dtypes: float64(7), int64(3), object(6)
memory usage: 3.3+ MB

In [ ]:
#Changing the data type of the date column
data["Date"]=pd.to_datetime(data["Date"], format="%d-%m-%Y")

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27114 entries, 0 to 27113
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         27114 non-null  object
 1   Rooms          27114 non-null  int64
 2   Type           27114 non-null  object
 3   SellerG        27114 non-null  object
 4   Date           27114 non-null  datetime64[ns]
 5   Distance       27113 non-null  float64
 6   Postcode       27113 non-null  float64
 7   Bedroom        20678 non-null  float64
 8   Bathroom       20672 non-null  float64
 9   Car            20297 non-null  float64
 10  Landsize       17873 non-null  float64
 11  BuildingArea   10543 non-null  object
 12  YearBuilt      11985 non-null  float64
 13  Regionname     27114 non-null  object
 14  Propertycount  27114 non-null  int64
 15  Price          27114 non-null  int64
dtypes: datetime64[ns](1), float64(7), int64(3), object(5)
memory usage: 3.3+ MB

In [ ]:
data.head()

,Suburb,Rooms,Type,SellerG,Date,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Regionname,Propertycount,Price
0,Airport West,3,t,Nelson,2016-09-03,13.500,3042.000,3.000,2.000,1.000,303.000,225,2016.000,Western Metropolitan,3464,840000
1,Albert Park,2,h,hockingstuart,2016-09-03,3.300,3206.000,2.000,1.000,0.000,120.000,82,1900.000,Southern Metropolitan,3280,1275000
2,Albert Park,2,h,Thomson,2016-09-03,3.300,3206.000,2.000,1.000,0.000,159.000,inf,NaN,Southern Metropolitan,3280,1455000
3,Alphington,4,h,Brace,2016-09-03,6.400,3078.000,3.000,2.000,4.000,853.000,263,1930.000,Northern Metropolitan,2211,2000000
4,Alphington,3,h,Jellis,2016-09-03,6.400,3078.000,3.000,2.000,2.000,208.000,inf,2013.000,Northern Metropolitan,2211,1110000

In [ ]:
#Why the Building Area column has object data type
data["BuildingArea"].unique()

array(['225', '82', 'inf', '263', '242', '251', '117', 'missing', '76',
       '399', '118', '103', '180', '123', '218', '129', '167', '154',
       '275', '121', nan, '125', '255', '75', '156', '240', '268', '108',
       '69', '140', '214', '253', '189', '215', '96', '104', '100', '313',
       '144', '93', '110', '70', '122', '51', '147', '113', '83', '56',
       '137', '85', '64', '175', '3558', '170', '265', '353', '138', '19',
       '116', '87', '74', '320', '300', '210', '120', '86', '97', '200',
       '106', '14', '161', '128', '185', '146', '133', '115', '143',
       '150', '195', '236', '276', '188', '179', '249', '141', '34', '73',
       '107', '84', '81', '207', '50', '264', '312', '235', '221', '183',
       '132', '160', '186', '78', '105', '145', '62', '220', '315', '181',
       '61', '112', '420', '226', '266', '410', '449', '356', '477',
       '250', '95', '190', '284', '247', '213', '209', '119', '111',
       '130', '348', '166', '44', '176', '98', '159', '79', '71', '60',
       '33', '89', '217', '127', '187', '109', '53', '201', '12', '63',
       '223', '102', '254', '327', '16', '165', '65', '139', '134', '280',
       '67', '272', '38', '153', '66', '152', '135', '374', '163', '124',
       '233', '39', '151', '279', '136', '405', '199', '158', '126', '80',
       '57', '36', '142', '77', '435', '92', '149', '114', '349', '178',
       '594', '274', '40', '68', '164', '204', '94', '257', '323', '314',
       '378', '55', '91', '309', '88', '58', '172', '211', '148', '49',
       '52', '174', '191', '335', '808', '168', '203', '520', '212',
       '222', '171', '228', '101', '267', '90', '196', '157', '99', '256',
       '15', '155', '162', '72', '252', '330', '177', '341', '197', '340',
       '182', '245', '270', '42', '229', '232', '131', '297', '237',
       '194', '173', '46', '360', '205', '45', '365', '321', '37', '304',
       '54', '305', '244', '43', '41', '22', '169', '59', '258', '230',
       '287', '618', '792', '355', '202', '395', '351', '325', '248',
       '224', '426', '286', '308', '198', '260', '291', '277', '281',
       '216', '262', '364', '30', '192', '47', '184', '25', '558', '362',
       '375', '347', '241', '475', '413', '400', '101.37', '219', '239',
       '123.21', '140.7481', '86.5', '30.6', '225.5', '322', '409.54',
       '26', '156.6', '227.6', '104.63', '193', '443', '167.13', '148.5',
       '270.18', '53.3', '98.5', '157.9351', '328', '94.3', '21', '310',
       '95.88', '261', '105.7', '72.9', '45.4', '221.3', '113.2',
       '186.75', '540', '127.8', '231', '106.4', '311', '234', '332',
       '206', '259', '246', '296', '269', '306', '380', '302', '48',
       '278', '35', '208', '467', '283', '458', '196.8', '106.2', '32',
       '424', '430', '243', '290', '511', '500', '531', '508', '333',
       '72.3', '66.23', '101.51', '292', '112.9', '99.5', '77.5', '293',
       '105.23', '352', '391', '121.8', '82.6', '136.49', '502', '680',
       '157.9352', '126.8', '100.6', '44.4', '151.54', '20', '397', '495',
       '331', '294', '334', '303', '318', '273', '584', '958', '288',
       '342', '354', '350', '465', '337', '317', '298', '529', '697',
       '289', '602', '6791', '534', '227', '429', '802', '373', '358',
       '238', '316', '393', '180.9', '826.8367', '366', '307', '625',
       '419', '94.5', '392', '28', '116.65', '11', '134.6', '282',
       '183.84', '431', '126.7', '18', '295', '390', '447', '271', '416',
       '370', '660', '463', '361', '496', '324', '173.45', '134.3',
       '464.3', '76.77', '113.76', '107.4', '255.79', '186.36', '490',
       '103.6', '63.7', '106.76', '39.5', '423', '319', '437', '285',
       '453', '472', '418', '487', '31', '301', '116.4', '182.85',
       '109.5', '129.7', '665', '398', '148.47', '553', '182.9', '184.75',
       '193.74', '68.5', '336', '346', '719', '3112', '414', '372', '525',
       '367', '1561', '454', '720', '329', '381', '677', '439', '857',
       '23', '503', '432', '377', '512', '425', '406', '389', '521',
       '6178', '654', '727', '417', '560', '168.01', '306.19', '515.78',
       '196.1', '789', '131.27', '167.87', '183.97', '199.5', '29', '446',
       '75.45', '165.5', '263.5', '585', '516', '345', '27', '444', '427',
       '326', '518', '13', '411', '1022', '339', '461', '376', '513',
       '836', '464', '386', '603', '613', '179.3', '142.6', '147.2',
       '225.98', '113.81', '401', '737', '530', '82.3', '110.87', '450',
       '673', '109.98', '122.25', '105.9', '101.7', '106.9', '93.82',
       '132.6', '154.3', '178.74', '88.3', '80.7', '89.25', '181.6',
       '104.4', '180.56', '123.5', '1143', '506', '575', '859', '653',
       '999', '445', '438', '686', '649', '736', '371.6122', '199.73',
       '118.54', '298.21', '169.5', '42.2', '135.5', '266.76', '272.4',
       '177.8', '139.4', '700', '766', '538', '528', '650', '368', '544',
       '557', '396', '638', '101.76', '363', '634', '195.0964', '470',
       '130.52', '547', '111.04', '63.4', '92.5', '115.96', '121.84',
       '122.86', '114.2', '266.53', '78.54', '85.35', '1041', '607',
       '478', '407', '344', '338', '501', '448', '357', '408', '412',
       '466', '739', '614', '421', '385', '68.11', '153.1', '85.2',
       '93.84', '124.45', '210.68', '200.71', '81.79', '934', '129.92',
       '43.7', '113.6', '66.32', '35.64', '61.6', '388.5', '672'],
      dtype=object)

It is difficult to analyze each point to find the categorical values in the column. Let's find the count of non-numeric values and see what are these values

In [ ]:
#Checking the count of different data types in BuildingArea column
data["BuildingArea"].apply(type).value_counts()

BuildingArea
<class 'float'>    16571
<class 'str'>      10543
Name: count, dtype: int64

It is made of mixed data type like 'missing', 'inf' which should actually be read as missing values (NaN). Let's replace such data with null values.

In [ ]:
#replacing values with nan
data["BuildingArea"]=data["BuildingArea"].replace(["missing", "inf"], np.nan)

In [ ]:
#changing the data type to float
data["BuildingArea"]=data["BuildingArea"].astype(float)

In [ ]:
#Let's check the data type of columns again
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27114 entries, 0 to 27113
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         27114 non-null  object
 1   Rooms          27114 non-null  int64
 2   Type           27114 non-null  object
 3   SellerG        27114 non-null  object
 4   Date           27114 non-null  datetime64[ns]
 5   Distance       27113 non-null  float64
 6   Postcode       27113 non-null  float64
 7   Bedroom        20678 non-null  float64
 8   Bathroom       20672 non-null  float64
 9   Car            20297 non-null  float64
 10  Landsize       17873 non-null  float64
 11  BuildingArea   10529 non-null  float64
 12  YearBuilt      11985 non-null  float64
 13  Regionname     27114 non-null  object
 14  Propertycount  27114 non-null  int64
 15  Price          27114 non-null  int64
dtypes: datetime64[ns](1), float64(8), int64(3), object(4)
memory usage: 3.3+ MB

It is also possible to replace missing and inf to NaN while loading  the data.

In [ ]:
#using na_values to tell python which values it should consider as NaN
path= "/content/drive/MyDrive/Week 1  Foundations Python and Statistics/Melbourne_Housing.csv"
data_new=pd.read_csv(path, na_values=["missing", "inf"],)

This method is useful when we know wgat kind of values to consider as anomalies in the data.

In [ ]:
data_new["BuildingArea"].dtype

dtype('float64')

We observe that now building area is being considered as float after the 'missing' and 'inf' were read as NaN

**What are missing values**

Missing values occur when no data value is stored for the variable in observation. Missing data are a common occurence and can have a significant effect on the conclusions that can be drawn from the data.

In [ ]:
#To check the unique values in BuildingArea column
data['BuildingArea'].unique()

array([ 225.    ,   82.    ,       nan,  263.    ,  242.    ,  251.    ,
        117.    ,   76.    ,  399.    ,  118.    ,  103.    ,  180.    ,
        123.    ,  218.    ,  129.    ,  167.    ,  154.    ,  275.    ,
        121.    ,  125.    ,  255.    ,   75.    ,  156.    ,  240.    ,
        268.    ,  108.    ,   69.    ,  140.    ,  214.    ,  253.    ,
        189.    ,  215.    ,   96.    ,  104.    ,  100.    ,  313.    ,
        144.    ,   93.    ,  110.    ,   70.    ,  122.    ,   51.    ,
        147.    ,  113.    ,   83.    ,   56.    ,  137.    ,   85.    ,
         64.    ,  175.    , 3558.    ,  170.    ,  265.    ,  353.    ,
        138.    ,   19.    ,  116.    ,   87.    ,   74.    ,  320.    ,
        300.    ,  210.    ,  120.    ,   86.    ,   97.    ,  200.    ,
        106.    ,   14.    ,  161.    ,  128.    ,  185.    ,  146.    ,
        133.    ,  115.    ,  143.    ,  150.    ,  195.    ,  236.    ,
        276.    ,  188.    ,  179.    ,  249.    ,  141.    ,   34.    ,
         73.    ,  107.    ,   84.    ,   81.    ,  207.    ,   50.    ,
        264.    ,  312.    ,  235.    ,  221.    ,  183.    ,  132.    ,
        160.    ,  186.    ,   78.    ,  105.    ,  145.    ,   62.    ,
        220.    ,  315.    ,  181.    ,   61.    ,  112.    ,  420.    ,
        226.    ,  266.    ,  410.    ,  449.    ,  356.    ,  477.    ,
        250.    ,   95.    ,  190.    ,  284.    ,  247.    ,  213.    ,
        209.    ,  119.    ,  111.    ,  130.    ,  348.    ,  166.    ,
         44.    ,  176.    ,   98.    ,  159.    ,   79.    ,   71.    ,
         60.    ,   33.    ,   89.    ,  217.    ,  127.    ,  187.    ,
        109.    ,   53.    ,  201.    ,   12.    ,   63.    ,  223.    ,
        102.    ,  254.    ,  327.    ,   16.    ,  165.    ,   65.    ,
        139.    ,  134.    ,  280.    ,   67.    ,  272.    ,   38.    ,
        153.    ,   66.    ,  152.    ,  135.    ,  374.    ,  163.    ,
        124.    ,  233.    ,   39.    ,  151.    ,  279.    ,  136.    ,
        405.    ,  199.    ,  158.    ,  126.    ,   80.    ,   57.    ,
         36.    ,  142.    ,   77.    ,  435.    ,   92.    ,  149.    ,
        114.    ,  349.    ,  178.    ,  594.    ,  274.    ,   40.    ,
         68.    ,  164.    ,  204.    ,   94.    ,  257.    ,  323.    ,
        314.    ,  378.    ,   55.    ,   91.    ,  309.    ,   88.    ,
         58.    ,  172.    ,  211.    ,  148.    ,   49.    ,   52.    ,
        174.    ,  191.    ,  335.    ,  808.    ,  168.    ,  203.    ,
        520.    ,  212.    ,  222.    ,  171.    ,  228.    ,  101.    ,
        267.    ,   90.    ,  196.    ,  157.    ,   99.    ,  256.    ,
         15.    ,  155.    ,  162.    ,   72.    ,  252.    ,  330.    ,
        177.    ,  341.    ,  197.    ,  340.    ,  182.    ,  245.    ,
        270.    ,   42.    ,  229.    ,  232.    ,  131.    ,  297.    ,
        237.    ,  194.    ,  173.    ,   46.    ,  360.    ,  205.    ,
         45.    ,  365.    ,  321.    ,   37.    ,  304.    ,   54.    ,
        305.    ,  244.    ,   43.    ,   41.    ,   22.    ,  169.    ,
         59.    ,  258.    ,  230.    ,  287.    ,  618.    ,  792.    ,
        355.    ,  202.    ,  395.    ,  351.    ,  325.    ,  248.    ,
        224.    ,  426.    ,  286.    ,  308.    ,  198.    ,  260.    ,
        291.    ,  277.    ,  281.    ,  216.    ,  262.    ,  364.    ,
         30.    ,  192.    ,   47.    ,  184.    ,   25.    ,  558.    ,
        362.    ,  375.    ,  347.    ,  241.    ,  475.    ,  413.    ,
        400.    ,  101.37  ,  219.    ,  239.    ,  123.21  ,  140.7481,
         86.5   ,   30.6   ,  225.5   ,  322.    ,  409.54  ,   26.    ,
        156.6   ,  227.6   ,  104.63  ,  193.    ,  443.    ,  167.13  ,
        148.5   ,  270.18  ,   53.3   ,   98.5   ,  157.9351,  328.    ,
         94.3   ,   21.    ,  310.    ,   95.88  ,  261.    ,  105.7   ,
         72.9   ,   45.4   ,  221.3   ,  113.2   ,  186.75  ,  540.    ,
        127.8   ,  231.    ,  106.4   ,  311.    ,  234.    ,  332.    ,
        206.    ,  259.    ,  246.    ,  296.    ,  269.    ,  306.    ,
        380.    ,  302.    ,   48.    ,  278.    ,   35.    ,  208.    ,
        467.    ,  283.    ,  458.    ,  196.8   ,  106.2   ,   32.    ,
        424.    ,  430.    ,  243.    ,  290.    ,  511.    ,  500.    ,
        531.    ,  508.    ,  333.    ,   72.3   ,   66.23  ,  101.51  ,
        292.    ,  112.9   ,   99.5   ,   77.5   ,  293.    ,  105.23  ,
        352.    ,  391.    ,  121.8   ,   82.6   ,  136.49  ,  502.    ,
        680.    ,  157.9352,  126.8   ,  100.6   ,   44.4   ,  151.54  ,
         20.    ,  397.    ,  495.    ,  331.    ,  294.    ,  334.    ,
        303.    ,  318.    ,  273.    ,  584.    ,  958.    ,  288.    ,
        342.    ,  354.    ,  350.    ,  465.    ,  337.    ,  317.    ,
        298.    ,  529.    ,  697.    ,  289.    ,  602.    , 6791.    ,
        534.    ,  227.    ,  429.    ,  802.    ,  373.    ,  358.    ,
        238.    ,  316.    ,  393.    ,  180.9   ,  826.8367,  366.    ,
        307.    ,  625.    ,  419.    ,   94.5   ,  392.    ,   28.    ,
        116.65  ,   11.    ,  134.6   ,  282.    ,  183.84  ,  431.    ,
        126.7   ,   18.    ,  295.    ,  390.    ,  447.    ,  271.    ,
        416.    ,  370.    ,  660.    ,  463.    ,  361.    ,  496.    ,
        324.    ,  173.45  ,  134.3   ,  464.3   ,   76.77  ,  113.76  ,
        107.4   ,  255.79  ,  186.36  ,  490.    ,  103.6   ,   63.7   ,
        106.76  ,   39.5   ,  423.    ,  319.    ,  437.    ,  285.    ,
        453.    ,  472.    ,  418.    ,  487.    ,   31.    ,  301.    ,
        116.4   ,  182.85  ,  109.5   ,  129.7   ,  665.    ,  398.    ,
        148.47  ,  553.    ,  182.9   ,  184.75  ,  193.74  ,   68.5   ,
        336.    ,  346.    ,  719.    , 3112.    ,  414.    ,  372.    ,
        525.    ,  367.    , 1561.    ,  454.    ,  720.    ,  329.    ,
        381.    ,  677.    ,  439.    ,  857.    ,   23.    ,  503.    ,
        432.    ,  377.    ,  512.    ,  425.    ,  406.    ,  389.    ,
        521.    , 6178.    ,  654.    ,  727.    ,  417.    ,  560.    ,
        168.01  ,  306.19  ,  515.78  ,  196.1   ,  789.    ,  131.27  ,
        167.87  ,  183.97  ,  199.5   ,   29.    ,  446.    ,   75.45  ,
        165.5   ,  263.5   ,  585.    ,  516.    ,  345.    ,   27.    ,
        444.    ,  427.    ,  326.    ,  518.    ,   13.    ,  411.    ,
       1022.    ,  339.    ,  461.    ,  376.    ,  513.    ,  836.    ,
        464.    ,  386.    ,  603.    ,  613.    ,  179.3   ,  142.6   ,
        147.2   ,  225.98  ,  113.81  ,  401.    ,  737.    ,  530.    ,
         82.3   ,  110.87  ,  450.    ,  673.    ,  109.98  ,  122.25  ,
        105.9   ,  101.7   ,  106.9   ,   93.82  ,  132.6   ,  154.3   ,
        178.74  ,   88.3   ,   80.7   ,   89.25  ,  181.6   ,  104.4   ,
        180.56  ,  123.5   , 1143.    ,  506.    ,  575.    ,  859.    ,
        653.    ,  999.    ,  445.    ,  438.    ,  686.    ,  649.    ,
        736.    ,  371.6122,  199.73  ,  118.54  ,  298.21  ,  169.5   ,
         42.2   ,  135.5   ,  266.76  ,  272.4   ,  177.8   ,  139.4   ,
        700.    ,  766.    ,  538.    ,  528.    ,  650.    ,  368.    ,
        544.    ,  557.    ,  396.    ,  638.    ,  101.76  ,  363.    ,
        634.    ,  195.0964,  470.    ,  130.52  ,  547.    ,  111.04  ,
         63.4   ,   92.5   ,  115.96  ,  121.84  ,  122.86  ,  114.2   ,
        266.53  ,   78.54  ,   85.35  , 1041.    ,  607.    ,  478.    ,
        407.    ,  344.    ,  338.    ,  501.    ,  448.    ,  357.    ,
        408.    ,  412.    ,  466.    ,  739.    ,  614.    ,  421.    ,
        385.    ,   68.11  ,  153.1   ,   85.2   ,   93.84  ,  124.45  ,
        210.68  ,  200.71  ,   81.79  ,  934.    ,  129.92  ,   43.7   ,
        113.6   ,   66.32  ,   35.64  ,   61.6   ,  388.5   ,  672.    ])

Checking missing values, duplicate values, and statistical summary

In [ ]:
#What are missing values?
#Missing values take place when no data value is stored for the variable in an observation.
#Missing data are a common occurence and can have a significant effect on the conclusions that can be drawn from the data

**Checking for missing value in the data**

In [ ]:
data.isnull().sum()

Suburb               0
Rooms                0
Type                 0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom           6436
Bathroom          6442
Car               6817
Landsize          9241
BuildingArea     16585
YearBuilt        15129
Regionname           0
Propertycount        0
Price                0
dtype: int64

**There are missing values in 8 columns of the data**

**We will treat these missing values after understanding the distributions of features in the data, the relationships that exist in the data. This will help us impute these values more effectively**

**Checking for duplicate entries in the data**

In [ ]:
data.duplicated().sum()

11

**This implies that there are 11 duplicate entries in the data that needs to be removed or speak with the owners of the data if they could fix that**

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27114 entries, 0 to 27113
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         27114 non-null  object
 1   Rooms          27114 non-null  int64
 2   Type           27114 non-null  object
 3   SellerG        27114 non-null  object
 4   Date           27114 non-null  datetime64[ns]
 5   Distance       27113 non-null  float64
 6   Postcode       27113 non-null  float64
 7   Bedroom        20678 non-null  float64
 8   Bathroom       20672 non-null  float64
 9   Car            20297 non-null  float64
 10  Landsize       17873 non-null  float64
 11  BuildingArea   10529 non-null  float64
 12  YearBuilt      11985 non-null  float64
 13  Regionname     27114 non-null  object
 14  Propertycount  27114 non-null  int64
 15  Price          27114 non-null  int64
dtypes: datetime64[ns](1), float64(8), int64(3), object(4)
memory usage: 3.3+ MB

In [ ]:
data.isnull()

,Suburb,Rooms,Type,SellerG,Date,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Regionname,Propertycount,Price
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27109,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27110,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
27111,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
27112,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False
27113,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
data.isnull().sum()

Suburb               0
Rooms                0
Type                 0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom           6436
Bathroom          6442
Car               6817
Landsize          9241
BuildingArea     16585
YearBuilt        15129
Regionname           0
Propertycount        0
Price                0
dtype: int64

we have 27k rows of data, and there are some missing values, we need to improve the data before we continue our analysis

**Check for duplicate entries in the data**

In [ ]:
data.duplicated().sum()

11

**11 duplicate entries in the data**

In [ ]:
#dropping duplicate entries from the data
data.drop_duplicates(inplace=True)

In [ ]:
#resetting the index of the data since some rows will be removed
data.reset_index(drop=True, inplace=True)

In [ ]:
data

,Suburb,Rooms,Type,SellerG,Date,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Regionname,Propertycount,Price
0,Airport West,3,t,Nelson,2016-09-03,13.500,3042.000,3.000,2.000,1.000,303.000,225.000,2016.000,Western Metropolitan,3464,840000
1,Albert Park,2,h,hockingstuart,2016-09-03,3.300,3206.000,2.000,1.000,0.000,120.000,82.000,1900.000,Southern Metropolitan,3280,1275000
2,Albert Park,2,h,Thomson,2016-09-03,3.300,3206.000,2.000,1.000,0.000,159.000,NaN,NaN,Southern Metropolitan,3280,1455000
3,Alphington,4,h,Brace,2016-09-03,6.400,3078.000,3.000,2.000,4.000,853.000,263.000,1930.000,Northern Metropolitan,2211,2000000
4,Alphington,3,h,Jellis,2016-09-03,6.400,3078.000,3.000,2.000,2.000,208.000,NaN,2013.000,Northern Metropolitan,2211,1110000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27098,Noble Park,3,h,C21,2017-09-30,22.700,3174.000,3.000,1.000,6.000,569.000,130.000,1959.000,South-Eastern Metropolitan,11806,627500
27099,Reservoir,3,u,RW,2017-09-30,12.000,3073.000,3.000,1.000,1.000,NaN,105.000,1990.000,Northern Metropolitan,21650,475000
27100,Roxburgh Park,4,h,Raine,2017-09-30,20.600,3064.000,4.000,2.000,2.000,NaN,225.000,1995.000,Northern Metropolitan,5833,591000
27101,Springvale South,3,h,Harcourts,2017-09-30,22.200,3172.000,3.000,2.000,1.000,544.000,NaN,NaN,South-Eastern Metropolitan,4054,780500
27102,Westmeadows,4,h,Barry,2017-09-30,16.500,3049.000,4.000,2.000,6.000,813.000,140.000,1960.000,Northern Metropolitan,2474,791000

**Let's check the summary of the data**

In [ ]:
data.describe()

,Rooms,Date,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Propertycount,Price
count,27103.000,27103,27102.000,27102.000,20678.000,20672.000,20297.000,17873.000,10529.000,11985.000,27103.000,27103.000
mean,2.992,2017-05-23 12:25:09.441759488,11.280,3113.787,3.046,1.592,1.716,560.537,154.512,1966.618,7564.741,1050664.131
min,1.000,2016-01-28 00:00:00,0.000,3000.000,0.000,0.000,0.000,50.000,11.000,1850.000,83.000,85000.000
25%,2.000,2016-11-19 00:00:00,6.400,3046.000,2.000,1.000,1.000,220.000,101.000,1950.000,4294.000,635000.000
50%,3.000,2017-07-08 00:00:00,10.500,3088.000,3.000,1.000,2.000,513.000,133.000,1970.000,6567.000,871000.000
75%,4.000,2017-10-28 00:00:00,14.000,3153.000,4.000,2.000,2.000,664.000,183.000,2000.000,10412.000,1300000.000
max,16.000,2018-03-17 00:00:00,48.100,3978.000,20.000,9.000,18.000,76000.000,6791.000,2019.000,21650.000,11200000.000
std,0.955,NaN,6.784,111.129,0.955,0.701,0.994,1411.309,130.584,36.042,4494.028,641660.161

In [ ]:
data.describe().T

,count,mean,min,25%,50%,75%,max,std
Rooms,27103.000,2.992,1.000,2.000,3.000,4.000,16.000,0.955
Date,27103,2017-05-23 12:25:09.441759488,2016-01-28 00:00:00,2016-11-19 00:00:00,2017-07-08 00:00:00,2017-10-28 00:00:00,2018-03-17 00:00:00,NaN
Distance,27102.000,11.280,0.000,6.400,10.500,14.000,48.100,6.784
Postcode,27102.000,3113.787,3000.000,3046.000,3088.000,3153.000,3978.000,111.129
Bedroom,20678.000,3.046,0.000,2.000,3.000,4.000,20.000,0.955
Bathroom,20672.000,1.592,0.000,1.000,1.000,2.000,9.000,0.701
Car,20297.000,1.716,0.000,1.000,2.000,2.000,18.000,0.994
Landsize,17873.000,560.537,50.000,220.000,513.000,664.000,76000.000,1411.309
BuildingArea,10529.000,154.512,11.000,101.000,133.000,183.000,6791.000,130.584
YearBuilt,11985.000,1966.618,1850.000,1950.000,1970.000,2000.000,2019.000,36.042
Propertycount,27103.000,7564.741,83.000,4294.000,6567.000,10412.000,21650.000,4494.028
Price,27103.000,1050664.131,85000.000,635000.000,871000.000,1300000.000,11200000.000,641660.161

In [ ]:
# total numbers of unique values in the postcode column
data["Postcode"].nunique()

209

In [ ]:
#Count and Percentage of Categoical Levels in each column

#Making a list of all categorical variables
cat_cols=["Suburb", "Type", "SellerG", "Regionname"]

In [ ]:
#Printing the count of unique categorical levels in each column
for column in cat_cols:
  print(data[column].value_counts())
  print("-"*50)

Suburb
Reservoir         724
Bentleigh East    493
Richmond          437
Preston           410
Brunswick         383
                 ...
Wandin North        1
Ferny Creek         1
Tecoma              1
Montrose            1
viewbank            1
Name: count, Length: 345, dtype: int64
--------------------------------------------------
Type
h    18394
u     5882
t     2827
Name: count, dtype: int64
--------------------------------------------------
SellerG
Nelson           2733
Jellis           2516
Barry            2385
hockingstuart    2096
Ray              1574
                 ...
Allan               1
Jim                 1
iProperty           1
Batty               1
Icon                1
Name: count, Length: 347, dtype: int64
--------------------------------------------------
Regionname
Southern Metropolitan         8480
Northern Metropolitan         7809
Western Metropolitan          5792
Eastern Metropolitan          3264
South-Eastern Metropolitan    1336
Northern Victoria              165
Eastern Victoria               163
Western Victoria                94
Name: count, dtype: int64
--------------------------------------------------

**There are two ways to handle missing values: Deleting the missing values and Imputting the missing values**

In [ ]:
#Printing the percentage of unique categorical levels in each column
for column in cat_cols:
  print(data[column].value_counts(normalize=True))
  print("-"*50)

Suburb
Reservoir        0.027
Bentleigh East   0.018
Richmond         0.016
Preston          0.015
Brunswick        0.014
                  ...
Wandin North     0.000
Ferny Creek      0.000
Tecoma           0.000
Montrose         0.000
viewbank         0.000
Name: proportion, Length: 345, dtype: float64
--------------------------------------------------
Type
h   0.679
u   0.217
t   0.104
Name: proportion, dtype: float64
--------------------------------------------------
SellerG
Nelson          0.101
Jellis          0.093
Barry           0.088
hockingstuart   0.077
Ray             0.058
                 ...
Allan           0.000
Jim             0.000
iProperty       0.000
Batty           0.000
Icon            0.000
Name: proportion, Length: 347, dtype: float64
--------------------------------------------------
Regionname
Southern Metropolitan        0.313
Northern Metropolitan        0.288
Western Metropolitan         0.214
Eastern Metropolitan         0.120
South-Eastern Metropolitan   0.049
Northern Victoria            0.006
Eastern Victoria             0.006
Western Victoria             0.003
Name: proportion, dtype: float64
--------------------------------------------------